apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
    argocd.argoproj.io/managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: 'quay.io/centos7/httpd-24-centos7:centos7'
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: httpd
    argocd.argoproj.io/managed-by: argocd
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
