apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvm
  labels:
    app: jvm
    argocd.argoproj.io/managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jvm
  template:
    metadata:
      labels:
        app: jvm
    spec:
      containers:
      - name: jvm
        image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jvm
  labels:
    app: jvm
    argocd.argoproj.io/managed-by: argocd
spec:
  selector:
    app: jvm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
